### ISSUE TITLE
安装 ArchWSL 并配置 | Artin's Blog

### ISSUE THREAD

**Issue by bytemain** [lengthmin/lengthmin.me#23]
https://lengthmin.me/posts/install-arch-wsl/ 

 用 windows 写代码最想吐槽的就是 cmd 了！WSL 真的就是吾等救星。之前使用的是商店里的 Ubuntu，没感觉到有啥不好的，然鹅试了 yuk7/ArchWSL 以后，能体会到 UbuntuWSL 是真的慢！链接：

**Comment by deamonssouls** [comment]
为什么我安装了以后进入bash都是提示拒绝访问？

**Comment by bytemain** [comment]
> @deamonssouls
> 为什么我安装了以后进入bash都是提示拒绝访问？

解压到哪里的呢？这个目录有写的权限吗？

**Comment by deamonssouls** [comment]
> @lengthmin
> > @deamonssouls
> > 为什么我安装了以后进入bash都是提示拒绝访问？
> 
> 解压到哪里的呢？这个目录有写的权限吗？

c盘根目录，后面我换了一个位置就可以了。
